"""Add company reviews

Revision ID: a7f72d0571fc
Revises: f2d4b6c8a9e1
Create Date: 2026-06-03 22:41:59.497360
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7f72d0571fc'
down_revision: Union[str, None] = 'f2d4b6c8a9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_reviews_company_id'), 'company_reviews', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_reviews_id'), 'company_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_company_reviews_user_id'), 'company_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_reviews_user_id'), table_name='company_reviews')
    op.drop_index(op.f('ix_company_reviews_id'), table_name='company_reviews')
    op.drop_index(op.f('ix_company_reviews_company_id'), table_name='company_reviews')
    op.drop_table('company_reviews')
    # ### end Alembic commands ###
